// ============================================================================
// Simpli Framework - Configuration Type System
// ============================================================================
// Every type used across the framework is defined here for single source of truth.
// This enables full TypeScript inference in simpli.config.ts via defineConfig().
// ============================================================================

// ---------------------------------------------------------------------------
// Navbar Types
// ---------------------------------------------------------------------------

export type NavbarItemPosition = 'left' | 'right';

export interface NavbarLogo {
  alt?: string;
  src: string;
  srcDark?: string;
  width?: number;
  height?: number;
  className?: string;
}

export interface NavbarLinkItem {
  type?: 'link';
  label: string;
  to?: string;
  href?: string;
  position?: NavbarItemPosition;
  icon?: string;
  className?: string;
  'aria-label'?: string;
}

export interface NavbarDocItem {
  type: 'doc';
  docId: string;
  label: string;
  position?: NavbarItemPosition;
}

export interface NavbarDropdownItem {
  type: 'dropdown';
  label: string;
  position?: NavbarItemPosition;
  items: Array<{
    label: string;
    to?: string;
    href?: string;
    icon?: string;
    description?: string;
  }>;
}

export interface NavbarSearchItem {
  type: 'search';
  position?: NavbarItemPosition;
}

export interface NavbarThemeToggleItem {
  type: 'themeToggle';
  position?: NavbarItemPosition;
}

export interface NavbarLocaleDropdownItem {
  type: 'localeDropdown';
  position?: NavbarItemPosition;
}

export interface NavbarVersionDropdownItem {
  type: 'versionDropdown';
  position?: NavbarItemPosition;
}

export type NavbarItem =
  | NavbarLinkItem
  | NavbarDocItem
  | NavbarDropdownItem
  | NavbarSearchItem
  | NavbarThemeToggleItem
  | NavbarLocaleDropdownItem
  | NavbarVersionDropdownItem;

export interface NavbarConfig {
  title?: string;
  logo?: NavbarLogo;
  items?: NavbarItem[];
  hideOnScroll?: boolean;
  style?: 'primary' | 'dark';
}

// ---------------------------------------------------------------------------
// Sidebar Types
// ---------------------------------------------------------------------------

export interface SidebarDocItem {
  type: 'doc';
  id: string;
  label?: string;
  className?: string;
  category?: string | null;
}

export interface SidebarLinkItem {
  type: 'link';
  label: string;
  href: string;
  className?: string;
}

export interface SidebarCategoryItem {
  type: 'category';
  label: string;
  collapsed?: boolean;
  collapsible?: boolean;
  className?: string;
  items: SidebarItem[];
  link?: {
    type: 'doc' | 'generated-index';
    id?: string;
    title?: string;
    description?: string;
  };
}

export interface SidebarAutogeneratedItem {
  type: 'autogenerated';
  dirName: string;
}

export type SidebarItem =
  | string // Shorthand - just doc ID
  | SidebarDocItem
  | SidebarLinkItem
  | SidebarCategoryItem
  | SidebarAutogeneratedItem;

export interface SidebarOptions {
  hideable?: boolean;
  autoCollapseCategories?: boolean;
}

export type SidebarsConfig = Record<string, SidebarItem[]>;

// ---------------------------------------------------------------------------
// Footer Types
// ---------------------------------------------------------------------------

export interface FooterLinkItem {
  label: string;
  to?: string;
  href?: string;
  icon?: string;
}

export interface FooterLinkColumn {
  title: string;
  items: FooterLinkItem[];
}

export interface FooterConfig {
  style?: 'light' | 'dark';
  logo?: NavbarLogo;
  links?: FooterLinkColumn[];
  copyright?: string;
}

// ---------------------------------------------------------------------------
// Color Mode Types
// ---------------------------------------------------------------------------

export type ColorMode = 'light' | 'dark';

export interface ColorModeConfig {
  defaultMode?: ColorMode;
  disableSwitch?: boolean;
  respectPrefersColorScheme?: boolean;
}

// ---------------------------------------------------------------------------
// Table of Contents Types
// ---------------------------------------------------------------------------

export interface TOCConfig {
  minHeadingLevel?: number;
  maxHeadingLevel?: number;
}

// ---------------------------------------------------------------------------
// Search Types
// ---------------------------------------------------------------------------

export interface AlgoliaSearchConfig {
  appId: string;
  apiKey: string;
  indexName: string;
  contextualSearch?: boolean;
}

export interface LocalSearchConfig {
  indexDocs?: boolean;
  indexBlog?: boolean;
  indexPages?: boolean;
  highlightSearchTerms?: boolean;
  maxResults?: number;
}

export interface SearchConfig {
  enabled?: boolean;
  provider?: 'local' | 'algolia';
  algolia?: AlgoliaSearchConfig;
  local?: LocalSearchConfig;
}

// ---------------------------------------------------------------------------
// Code Block Types
// ---------------------------------------------------------------------------

export interface MagicComment {
  className: string;
  line: string;
}

export interface CodeBlockConfig {
  showLineNumbers?: boolean;
  theme?: {
    light?: string;
    dark?: string;
  };
  magicComments?: MagicComment[];
}

// ---------------------------------------------------------------------------
// Announcement Bar Types
// ---------------------------------------------------------------------------

export interface AnnouncementBarConfig {
  id: string;
  content: string;
  backgroundColor?: string;
  textColor?: string;
  isCloseable?: boolean;
}

// ---------------------------------------------------------------------------
// Theme Configuration
// ---------------------------------------------------------------------------

export interface MetaTag {
  name?: string;
  property?: string;
  content: string;
}

export interface ThemeConfig {
  navbar?: NavbarConfig;
  sidebar?: SidebarOptions;
  footer?: FooterConfig;
  colorMode?: ColorModeConfig;
  tableOfContents?: TOCConfig;
  search?: SearchConfig;
  codeBlock?: CodeBlockConfig;
  announcementBar?: AnnouncementBarConfig;
  metadata?: MetaTag[];
  customCss?: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Internationalization Types
// ---------------------------------------------------------------------------

export interface LocaleConfig {
  label: string;
  direction?: 'ltr' | 'rtl';
  htmlLang?: string;
  calendar?: string;
  path?: string;
}

export interface I18nConfig {
  defaultLocale: string;
  locales: string[];
  localeConfigs?: Record<string, LocaleConfig>;
  path?: string;
}

// ---------------------------------------------------------------------------
// Markdown Options
// ---------------------------------------------------------------------------

export type RemarkPlugin = [unknown, Record<string, unknown>] | unknown;
export type RehypePlugin = [unknown, Record<string, unknown>] | unknown;

export interface MarkdownConfig {
  format?: 'mdx' | 'md' | 'detect';
  remarkPlugins?: RemarkPlugin[];
  rehypePlugins?: RehypePlugin[];
  mermaid?: boolean;
  math?: boolean;
}

// ---------------------------------------------------------------------------
// Versioning Types
// ---------------------------------------------------------------------------

export interface VersionConfig {
  label: string;
  path?: string;
  banner?: 'none' | 'unreleased' | 'unmaintained';
  badge?: boolean;
}

export interface VersioningConfig {
  enabled?: boolean;
  versions?: Record<string, VersionConfig>;
  lastVersion?: string;
}

// ---------------------------------------------------------------------------
// Build Options
// ---------------------------------------------------------------------------

export interface BuildConfig {
  outDir?: string;
  trailingSlash?: boolean;
  noIndex?: boolean;
}

// ---------------------------------------------------------------------------
// Plugin Types (External Reference)
// ---------------------------------------------------------------------------

export interface SimpliPluginInstance {
  name: string;
  version?: string;
  configLoaded?(config: SimpliConfig): SimpliConfig | void;
  contentLoaded?(args: ContentLoadedArgs): void | Promise<void>;
  routesResolved?(routes: RouteConfig[]): RouteConfig[];
  postBuild?(args: PostBuildArgs): void | Promise<void>;
  getThemeComponents?(): Record<string, import('react').ComponentType>;
  getClientModules?(): string[];
  extendMarkdown?(md: MarkdownConfig): MarkdownConfig;
  transformContent?(content: string, filePath: string): string;
}

export interface ContentLoadedArgs {
  content: {
    docs: DocMetadata[];
    blog?: BlogPostMetadata[];
  };
  addRoute: (route: RouteConfig) => void;
  createData: (name: string, data: string) => Promise<string>;
}

export interface PostBuildArgs {
  outDir: string;
  routesPaths: string[];
  siteConfig: SimpliConfig;
}

export type PluginConfig =
  | SimpliPluginInstance
  | [string, Record<string, unknown>]
  | string;

// ---------------------------------------------------------------------------
// Content Metadata Types
// ---------------------------------------------------------------------------

export interface DocMetadata {
  id: string;
  title: string;
  description?: string;
  slug: string;
  permalink: string;
  sidebarLabel?: string;
  sidebarPosition?: number;
  tags?: string[];
  keywords?: string[];
  image?: string;
  hideTitle?: boolean;
  hideTableOfContents?: boolean;
  draft?: boolean;
  unlisted?: boolean;
  paginationPrev?: string | null;
  paginationNext?: string | null;
  customEditUrl?: string;
  lastUpdate?: {
    date: string;
    author?: string;
  };
  source: string;
  contentPath: string;
}

export interface BlogPostMetadata {
  id: string;
  title: string;
  description?: string;
  slug: string;
  permalink: string;
  date: string;
  authors?: BlogAuthor[];
  tags?: string[];
  image?: string;
  draft?: boolean;
  readingTime?: number;
  source: string;
}

export interface BlogAuthor {
  name: string;
  title?: string;
  url?: string;
  imageUrl?: string;
}

// ---------------------------------------------------------------------------
// Route Types
// ---------------------------------------------------------------------------

export interface RouteConfig {
  path: string;
  component: string;
  exact?: boolean;
  metadata?: Record<string, unknown>;
  children?: RouteConfig[];
}

// ---------------------------------------------------------------------------
// Main Configuration Interface
// ---------------------------------------------------------------------------

export interface SimpliConfig {
  // Required
  title: string;

  // Site metadata
  tagline?: string;
  url?: string;
  baseUrl?: string;
  favicon?: string;

  // Organization
  organizationName?: string;
  projectName?: string;

  // Content directories
  docsDir?: string;
  blogDir?: string;
  pagesDir?: string;
  staticDir?: string;

  // Features
  i18n?: I18nConfig;
  themeConfig?: ThemeConfig;
  markdown?: MarkdownConfig;
  versioning?: VersioningConfig;
  build?: BuildConfig;

  // Plugins
  plugins?: PluginConfig[];

  // Sidebars
  sidebars?: SidebarsConfig;

  // Custom data
  customFields?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// defineConfig helper type
// ---------------------------------------------------------------------------

export type SimpliUserConfig = SimpliConfig;
